<div id="main_container" class="content-wrapper">
</div>
<?php
$this->load->view('main/dashboard_templates');
$this->load->view('main/users_templates');
$this->load->view('main/logs_templates');
$this->load->view('main/income_certificate_templates');
$this->load->view('main/active_users_templates');
$this->load->view('main/vp_users_templates');
$this->load->view('main/domicile_templates');
$this->load->view('main/heirship_templates');
$this->load->view('main/caste_certificate_templates');
$this->load->view('main/obc_certificate_templates');
$this->load->view('main/na_application_templates');
$this->load->view('main/ncl_certificate_templates');
$this->load->view('main/ews_certificate_templates');
$this->load->view('main/form_one_fourteen_templates');
$this->load->view('main/form_three_templates');
$this->load->view('main/form_five_templates');
$this->load->view('main/form_nine_templates');
$this->load->view('main/certified_copy_templates');
$this->load->view('main/rti_templates');
$this->load->view('main/character_certificate_templates');
$this->load->view('main/dapvr_case_templates');
$this->load->view('main/arrears_update_templates');
$this->load->view('main/document_registration_templates');
$this->load->view('main/khata_number_templates');
$this->load->view('main/circle_rate_templates');
$this->load->view('main/landtax_na_templates');
$this->load->view('main/eocs_site_plan_templates');
$this->load->view('main/property_card_templates');
$this->load->view('main/eocs_site_plan_rural_templates');
$this->load->view('main/department_templates');
$this->load->view('main/service_templates');
$this->load->view('main/marriage_certificate_templates');
$this->load->view('main/svamitva_ror_templates');
$this->load->view('main/birth_certificate_templates');
$this->load->view('main/death_certificate_templates');
$this->load->view('main/landtax_agriculture_templates');
$this->load->view('main/general_application_templates');
?>
